[colors]
[colors.primary]
background = "#000000"
foreground = "#f8e45c"

[colors.normal]
black   = "#000000"
red     = "#ff4e96"
green   = "#3bab18"
yellow  = "#ff882b"
blue    = "#00a6f2"
magenta = "#af79ff"
cyan    = "#00c2d3"
white   = "#f8e45c"

[colors.bright]
black   = "#897100"
red     = "#ff4e96"
green   = "#3bab18"
yellow  = "#ff882b"
blue    = "#00a6f2"
magenta = "#af79ff"
cyan    = "#00c2d3"
white   = "#ffffff"

[colors.cursor]
text   = "#000000"
cursor = "#f8e45c"
