# Background and foreground colors
background = #000000
foreground = #f8e45c

# Standard colors
palette = 0=#000000
palette = 1=#ff4e96
palette = 2=#3bab18
palette = 3=#ff882b
palette = 4=#00a6f2
palette = 5=#af79ff
palette = 6=#00c2d3
palette = 7=#f8e45c

# Bright colors
palette = 8=#897100
palette = 9=#ff4e96
palette = 10=#3bab18
palette = 11=#ff882b
palette = 12=#00a6f2
palette = 13=#af79ff
palette = 14=#00c2d3
palette = 15=#ffffff
