background            #000000
foreground            #f8e45c

# black
color0  #000000
color8  #816d26

# red
color1  #ff4e96
color9  #ff4e96

# green
color2  #3ba900
color10 #3ba900

# yellow
color3  #e27f00
color11 #e27f00

# blue
color4  #00a6f2
color12 #00a6f2

# magenta
color5  #af79ff
color13 #af79ff

#cyan
color6  #24B0B5
color14 #24B0B5

#white
color7  #f8e45c
color15 #f8e45c


