background            #000000
foreground            #f8e45c

# black
color0  #000000
color8  #897100

# red
color1  #ff4e96
color9  #ff4e96

# green
color2  #3bab18
color10 #3bab18

# yellow
color3  #ff882b
color11 #ff882b

# blue
color4  #00a6f2
color12 #00a6f2

# magenta
color5  #af79ff
color13 #af79ff

#cyan
color6  #00c2d3
color14 #00c2d3

#white
color7  #f8e45c
color15 #ffffff


